# Generated by Django 6.0.3 on 2026-03-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('location_type', models.CharField(choices=[('study', 'Study Space'), ('sweet_treat', 'Sweet Treat')], default='study', max_length=20)),
                ('google_place_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='StudyLocations',
        ),
    ]
