# Generated by Django 6.0.3 on 2026-03-07 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0003_searchedcoordinates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchedcoordinates',
            old_name='lat',
            new_name='lati',
        ),
        migrations.RenameField(
            model_name='searchedcoordinates',
            old_name='lng',
            new_name='longi',
        ),
    ]
