# Generated by Django 6.0.3 on 2026-04-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0004_rename_lat_searchedcoordinates_lati_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinnerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('prize', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
