# Generated by Django 6.0.3 on 2026-03-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venting_machine', models.BooleanField(default=False)),
                ('microwave', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=False)),
                ('aircon', models.BooleanField(default=False)),
                ('toilets', models.BooleanField(default=False)),
                ('hottap', models.BooleanField(default=False)),
                ('meetingroom', models.BooleanField(default=False)),
                ('printer', models.BooleanField(default=False)),
                ('pcs', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Studyspaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('indoors', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('temperature', models.CharField(choices=[('Artic', 'Artic'), ('Intense aircon', 'Intense aircon'), ('Just right', 'Just right'), ('Nice and toasty', 'Nice and toasty'), ('Sahara Desert', 'Sahara Desert')], max_length=1000)),
                ('plugsockets', models.BooleanField(default=False)),
                ('windows', models.CharField(choices=[('Bat cave', 'Bat cave'), ('Airplane window', 'Airplane window'), ('Have to go on a bear hunt to find', 'Have to go on a bear hunt to find'), ('Green house', 'Green house')], max_length=1000)),
                ('sound', models.CharField(choices=[('Pin drop', 'Pin drop'), ('Social space', 'Social space'), ('Mothers meeting', 'Mothers meeting')], max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('ambience', models.CharField(choices=[('Dark academia', 'Dark academia'), ('warm and cosy', 'warm and cosy'), ('corporate', 'Corporate '), ('Millennium core', 'Millennium core'), ('Bare bones', 'Bare bones'), ('Brutalistic', 'Brutslistic')], max_length=1000)),
                ('in_house_food', models.BooleanField(default=False)),
                ('pay_to_enter', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('accessibility', models.BooleanField(default=False)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
            ],
        ),
    ]
