# Generated by Django 6.0.3 on 2026-03-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilities',
            name='aircon',
        ),
        migrations.RemoveField(
            model_name='facilities',
            name='hottap',
        ),
        migrations.RemoveField(
            model_name='facilities',
            name='meetingroom',
        ),
        migrations.RemoveField(
            model_name='facilities',
            name='microwave',
        ),
        migrations.RemoveField(
            model_name='facilities',
            name='pcs',
        ),
        migrations.RemoveField(
            model_name='facilities',
            name='printer',
        ),
        migrations.RemoveField(
            model_name='facilities',
            name='toilets',
        ),
        migrations.RemoveField(
            model_name='facilities',
            name='venting_machine',
        ),
        migrations.RemoveField(
            model_name='facilities',
            name='water',
        ),
        migrations.AddField(
            model_name='facilities',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
