# Generated by Django 6.0.3 on 2026-03-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_remove_facilities_aircon_remove_facilities_hottap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyspaces',
            name='accessibility',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='studyspaces',
            name='ambience',
            field=models.CharField(blank=True, choices=[('Dark academia', 'Dark academia'), ('warm and cosy', 'warm and cosy'), ('corporate', 'Corporate '), ('Millennium core', 'Millennium core'), ('Bare bones', 'Bare bones'), ('Brutalistic', 'Brutslistic')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='studyspaces',
            name='in_house_food',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='studyspaces',
            name='indoors',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='studyspaces',
            name='pay_to_enter',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='studyspaces',
            name='public',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='studyspaces',
            name='sound',
            field=models.CharField(blank=True, choices=[('Pin drop', 'Pin drop'), ('Social space', 'Social space'), ('Mothers meeting', 'Mothers meeting')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='studyspaces',
            name='temperature',
            field=models.CharField(blank=True, choices=[('Artic', 'Artic'), ('Intense aircon', 'Intense aircon'), ('Just right', 'Just right'), ('Nice and toasty', 'Nice and toasty'), ('Sahara Desert', 'Sahara Desert')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='studyspaces',
            name='wifi',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='studyspaces',
            name='windows',
            field=models.CharField(blank=True, choices=[('Bat cave', 'Bat cave'), ('Airplane window', 'Airplane window'), ('Have to go on a bear hunt to find', 'Have to go on a bear hunt to find'), ('Green house', 'Green house')], max_length=1000, null=True),
        ),
    ]
