# Generated by Django 6.0.3 on 2026-03-08 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0004_rename_lat_searchedcoordinates_lati_and_more'),
        ('projectApp', '0003_alter_studyspaces_accessibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyspaces',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_info', to='map_app.locations'),
        ),
    ]
