# Generated by Django 6.0.3 on 2026-04-27 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0005_winnerlog'),
        ('projectApp', '0004_studyspaces_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyspaces',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='studyspaces',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_info', to='map_app.locations'),
        ),
    ]
