# Generated by Django 6.0.3 on 2026-03-08 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0004_rename_lat_searchedcoordinates_lati_and_more'),
        ('projectApp', '0004_studyspaces_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyspaces',
            name='location',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='study_info', to='map_app.locations'),
            preserve_default=False,
        ),
    ]
